[package]
name = "game_blinder"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.1"
inputbot = "0.6.0"
log = "0.4.22"
pixels = "0.13.0"
simple-logging = "2.0.2"
winit = {version = "0.30.3", features = ["rwh_05"]}

[features]
rwh_05 = []
